apiVersion: v1
kind: Service
metadata:
  name: sample-app-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: kube-sample-app
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP